# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0024_pausetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salespoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servery',
            name='salespoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='queue.Salespoint'),
        ),
    ]
